name: Build
on:
  workflow_dispatch:
  push:
    branches: [ "**" ]
env:
  compile-flags: "-c Release"
jobs:
  main:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get Time
      run: |
        echo "TIME=$(Get-Date -Format "yyyy-MM-ddTHH:mm:sszzz")" >> $env:GITHUB_ENV
    - name: Publish
      run: dotnet publish YMCL.Main/YMCL.Main.csproj -r win-x86 --self-contained false
    - name: Create GitHub Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.TOKEN }}"
        title: "Release By Github Actions - $env:TIME"
        automatic_release_tag: "Auto-Release"
        prerelease: true
        files: |
          YMCL.Main/bin/Release/net8.0-windows/win-x86/publish/*

