name: CI-Build
on:
  workflow_dispatch:
  push:
    branches: [ "**" ]
env:
  compile-flags: "-c Release"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Test
      run: dotnet test YMCL.Main/YMCL.Main.csproj
  test_build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Test
      run: dotnet build YMCL.Main/YMCL.Main.csproj
  build:
    runs-on: ubuntu-latest
    needs: [test, test_build]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Build
      run: dotnet build YMCL.Main/YMCL.Main.csproj ${{ env.compile-flags }}
