name: CI-Build
on:
  workflow_dispatch:
  push:
    branches: [ "**" ]
env:
  compile-flags: "-c Release"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Build
      run: dotnet build YMCL.Main/YMCL.Main.csproj
