name: Build
on:
  workflow_dispatch:
  push:
    branches: [ "**" ]
env:
  compile-flags: "-c Release"
jobs:
  main:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Publish
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      # run: dotnet publish YMCL.Main/YMCL.Main.csproj -r win-x86 --self-contained false
    # - name: Create GitHub Release
    #   uses: marvinpinto/action-automatic-releases@latest
    #   with:
    #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
    #     automatic_release_tag: ${{ env.ReleaseVersion }}
    #     title: ${{ env.ReleaseVersion }}
    #     prerelease: true
    #     files: |
    #       artifacts/packages/*

