name: .NET Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ mian ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # 安装 .NET Core
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0

    # 编译整个项目
    - name: Build the solution
      run: dotnet build

