name: Publish
on:
  workflow_dispatch:
  push:
    branches: [ "**" ]
env:
  compile-flags: "-c Release"
jobs:
  main:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Build
      run: |
        dotnet publish YMCL.Main/YMCL.Main.csproj -r win-x86 --self-contained false
        dotnet publish YMCL.Main/YMCL.Main.csproj -r win-x64 --self-contained false
    - name: Rename
      run: |
        mv ./YMCL.Main/bin/Release/net8.0-windows/win-x86/publish/YMCL.Main.exe ./YMCL.Main/bin/Release/net8.0-windows/win-x86/publish/YMCL.Main.x86.exe
        mv ./YMCL.Main/bin/Release/net8.0-windows/win-x64/publish/YMCL.Main.exe ./YMCL.Main/bin/Release/net8.0-windows/win-x64/publish/YMCL.Main.x64.exe
    - name: Publish
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.TOKEN }}
        allowUpdates: true # 覆盖文件
        prerelease: true # 预发布 别人可以看到 版本号会继续加
        tag: ${{ github.event.commits[0].timestamp }}
        body: Release By Github Actions - ${{ github.event.commits[0].timestamp }}
        artifacts: "./YMCL.Main/bin/Release/net8.0-windows/win-x64/publish/*,./YMCL.Main/bin/Release/net8.0-windows/win-x86/publish/*"
        
