name: Publish
on:
  workflow_dispatch:
  push:
    branches: [ "**" ]
env:
  compile-flags: "-c Release"
jobs:
  main:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Publish
      run: |
        dotnet publish YMCL.Main/YMCL.Main.csproj -r win-x86 --self-contained false
        dotnet publish YMCL.Main/YMCL.Main.csproj -r win-x64 --self-contained false
    - name: Rename
      run: |
        mv ./YMCL/YMCL.Main/bin/Release/net8.0-windows/win-x86/publish/YMCL.Main.exe ./YMCL/YMCL.Main/bin/Release/net8.0-windows/win-x86/publish/YMCL.Main.x86.exe
        mv ./YMCL/YMCL.Main/bin/Release/net8.0-windows/win-x64/publish/YMCL.Main.exe ./YMCL/YMCL.Main/bin/Release/net8.0-windows/win-x64/publish/YMCL.Main.x64.exe
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: "Auto-Release"
        release_name: Release By Github Actions - ${{ github.event.commits[0].timestamp }}
        body: New Release
        draft: false
        prerelease: true

    - name: Upload Release Asset - 1
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./YMCL/YMCL.Main/bin/Release/net8.0-windows/win-x86/publish
        asset_name: YMCL.Main.x86.exe
        asset_content_type: application/octet-stream

    - name: Upload Release Asset - 2
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./YMCL/YMCL.Main/bin/Release/net8.0-windows/win-x64/publish
        asset_name: YMCL.Main.x64.exe
        asset_content_type: application/octet-stream

