name: Publish
on:
  workflow_dispatch:
  push:
    branches: [ "**" ]
env:
  compile-flags: "-c Release"
  TagName: " ${{ github.event.commits[0].timestamp }} "
jobs:
  main:
    runs-on: windows-latest
    steps:
    # - name: Checkout
    #   uses: actions/checkout@v3
    #   with:
    #     fetch-depth: 0
    # - name: Build
    #   run: |
    #     dotnet publish YMCL.Main/YMCL.Main.csproj -r win-x86 --self-contained false
    #     dotnet publish YMCL.Main/YMCL.Main.csproj -r win-x64 --self-contained false
    # - name: Rename
    #   run: |
    #     mv ./YMCL.Main/bin/Release/net8.0-windows/win-x86/publish/YMCL.Main.exe ./YMCL.Main/bin/Release/net8.0-windows/win-x86/publish/YMCL.Main.x86.exe
    #     mv ./YMCL.Main/bin/Release/net8.0-windows/win-x64/publish/YMCL.Main.exe ./YMCL.Main/bin/Release/net8.0-windows/win-x64/publish/YMCL.Main.x64.exe
    - name: Tag 
      uses: rickstaa/action-create-tag@v1
      id: "tag_create"
      with:
        tag: "Github Actions - ${{ github.event.commits[0].timestamp }}"
    # - name: Publish
    #   uses: marvinpinto/action-automatic-releases@latest
    #   with:
    #     repo_token: "${{ secrets.TOKEN }}"
    #     title: "Release By Github Actions - ${{ github.event.commits[0].timestamp }}"
    #     automatic_release_tag: "${{ github.ref }}"
    #     prerelease: true
    #     files: |
    #       YMCL.Main/bin/Release/net8.0-windows/win-x86/publish/*
    #       YMCL.Main/bin/Release/net8.0-windows/win-x64/publish/*
        
