name: Publish
on:
  workflow_dispatch:
  push:
    branches: [ "**" ]
  
jobs:
  main:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Time
      id: date
      run: |
        echo "date=$(date +'%Y-%m-%d.%H-%M-%S')" >> $GITHUB_OUTPUT
        echo "$(date +'%Y.%m.%d.%H.%M')" > ./YMCL.Main/Public/Text/DateTime.txt
      shell: bash
    - name: Build
      run: |
        dotnet publish YMCL.Main/YMCL.Main.csproj -r win-x86 --self-contained false
        dotnet publish YMCL.Main/YMCL.Main.csproj -r win-x64 --self-contained false
    - name: Rename
      run: |
        mv ./YMCL.Main/bin/Release/net8.0-windows7.0/win-x86/publish/YMCL.Main.exe ./YMCL.Main/bin/Release/net8.0-windows7.0/win-x86/publish/YMCL.Main.x86.exe
        mv ./YMCL.Main/bin/Release/net8.0-windows7.0/win-x64/publish/YMCL.Main.exe ./YMCL.Main/bin/Release/net8.0-windows7.0/win-x64/publish/YMCL.Main.x64.exe
    - name: Publish
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.TOKEN }}"
        title: "${{ github.event.commits[0].message }}"
        automatic_release_tag: "AutoRelease-${{ steps.date.outputs.date }}"
        prerelease: true
        files: |
          YMCL.Main/bin/Release/net8.0-windows7.0/win-x86/publish/*
          YMCL.Main/bin/Release/net8.0-windows7.0/win-x64/publish/*
        
